apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: edge-app
  namespace: cluster-config
spec:
  targetNamespace: edge-app
  releaseName: edge-app
  chart:
    spec:
      chart: edge-app-helloworld
      sourceRef:
        kind: HelmRepository
        name: acr
        namespace: cluster-config
      version: "0.1.0"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    serviceType: ClusterIP
    imageRepo: acrrfp000.azurecr.io
